### PR TITLE
Update phone number restrictions and field bugs

### LINKED ISSUE #75: [PE-D][Tester B] Exit command will cause java.nio.file.AccessDeniedException
-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: ThomasHoooo/ped#1

### LINKED ISSUE #105: [PE-D][Tester A] Format of number not fixed
Possible to put invalid number. I understand that people may have universal numbers technically can constrain to all legal numbers. Else might want to specify only Sg numbers allowed that starts with 9/8 with 8 numbers.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: PokezardVGC/ped#9

### PR DESCRIPTION
**Pull request by Eclipse-Dominator**
- Fixes #105 
- Fixes #75 
- Fixes bug where field add is not checking for duplicate 
- Fixes bug where field error messages are inconsistent
- Fixes bug where description of task cannot be edited

### CODE REVIEW

File: src/main/java/seedu/address/logic/LogicManager.java [hunk 1]
```diff
@@ -25,15 +26,19 @@
  */
 public class LogicManager implements Logic {
     public static final String FILE_OPS_ERROR_MESSAGE = "Could not save data to file: ";
+
+    private static final String PERM_ERR =
+        "Unable to save your information!\nPlease check the FAQ section of the user guide for more information."
+            + "The user guide can be accessed through Help in the menu. \n%s";
```
Comment (autumn-sonata) [inline src/main/java/seedu/address/logic/LogicManager.java:32]: Helpful command for users to look at user guide for help.

File: src/main/java/seedu/address/logic/commands/fields/AddFieldCommand.java [hunk 2]
```diff
@@ -10,14 +10,18 @@
...
 
     public static final String SUBCOMMAND_WORD = "add";
 
     public static final String MESSAGE_USAGE = getFullCommand(SUBCOMMAND_WORD)
         + " :Assigns an attribute to a given item.\n"
-        + getFullCommand(SUBCOMMAND_WORD) + "[t|u|g]/id [type] [value] [settings] [styleflags]";
+        + getFullCommand(SUBCOMMAND_WORD) + " [t|u|g]/id [type] [value]\n"
+        + "e.g. field add t/1 bug low severity\n"
+        + " OR task select 1 field add bug low severity\n"
+        + "Adds a new custom field called bug to attribute";
```
Comment (autumn-sonata) [inline src/main/java/seedu/address/logic/commands/fields/AddFieldCommand.java:24]: Helpful comments for user to understand the formatting of commands from the application itself.

File: src/test/java/seedu/address/model/person/PhoneTest.java [hunk 3]
```diff
@@ -32,11 +32,20 @@ public void isValidPhone() {
...
+        assertTrue(Phone.isValidPhone("65 123123")); // optional + for contry code
+        assertTrue(Phone.isValidPhone("+543  123123")); // additional spacings
+        assertTrue(Phone.isValidPhone("111")); // short number
+        assertTrue(Phone.isValidPhone("+65 83010000")); // with country code
+        assertTrue(Phone.isValidPhone("+1 133 10230002")); // with country code and area code
+        assertTrue(Phone.isValidPhone("+1113 3133 102")); // with country code and area code
+        assertTrue(Phone.isValidPhone("+1113 3133 102123123123123")); // with country code and area code
+        assertTrue(Phone.isValidPhone("11115869"));
+        assertTrue(Phone.isValidPhone("124293842033123")); // long phone numbers
+        assertTrue(Phone.isValidPhone("9312 1534")); // spaces within digits
```
Comment (autumn-sonata) [inline src/test/java/seedu/address/model/person/PhoneTest.java:48]: Good testing on the which `Phone` numbers are accepted.

**Review by autumn-sonata — APPROVED** [review]
LGTM! Testing on phone number restrictions are properly done and bugs from the Pe dry run were fixed.
