### PR TITLE
Fix PE-D bugs

### LINKED ISSUE #105: [PE-D][Tester A] Format of number not fixed
Possible to put invalid number. I understand that people may have universal numbers technically can constrain to all legal numbers. Else might want to specify only Sg numbers allowed that starts with 9/8 with 8 numbers.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: PokezardVGC/ped#9

### LINKED ISSUE #108: [PE-D][Tester A] Unexpected error message for adding existing user to group he/she has been assigned
Should display user is already in said group instead of above error message

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: PokezardVGC/ped#10

### LINKED ISSUE #129: [PE-D][Tester C] Evidence of print statements in application
Not sure if it's a big issue, but I noticed there were some print statements throughout the application. 

For example:

It seems that there are a few `System.out.println` calls in `SelectPersonCommandParser`and `IfCommandParser`. Might be good to clean up the code for code quality!

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: misterpuffin/ped#7

### LINKED ISSUE #137: [PE-D][Tester D] Command cannot be executed but does not show an error message
As can be seen, trying to create a task with no title is not allowed as pressing the enter key does nothing. However, no error message is shown to explain this behaviour. 

The message currently being shown is from a previous successful attempt to add a task.

The feature does not work as intended.

Since creating tasks is a major feature of this product, this is a significant inconvenience.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: nickeltea/ped#12

### PR DESCRIPTION
**Pull request by connlim**
Fixes #105
Fixes #108
Fixes #129 
Fixes #137

### CODE REVIEW

File: src/main/java/seedu/address/model/attribute/Phone.java [hunk 1]
```diff
@@ -7,15 +7,15 @@
...
  */
 public class Phone extends AbstractAttribute<String> implements PrefixedAttribute {
 
     public static final String TYPE = "Phone";
-    public static final String MESSAGE_CONSTRAINTS = "Phone numbers should only contain numbers,"
-        + " and it should be at least 3 digits long";
-    public static final String VALIDATION_REGEX = "\\d{3,}";
+    public static final String MESSAGE_CONSTRAINTS =
+            "Phone numbers should only contain numbers, start with 6, 8 or 9, and be 8 digits long";
+    public static final String VALIDATION_REGEX = "[689]\\d{7}";
```
Comment (Eclipse-Dominator) [inline src/main/java/seedu/address/model/attribute/Phone.java:18]: This is a bit too restrictive on the end user, I think I will update the phone validation regex to be more robust later.

**Review by Eclipse-Dominator — APPROVED** [review]
lgtm!

File: src/main/java/seedu/address/model/attribute/Phone.java (hunk 1 above)
Comment (connlim) [reply src/main/java/seedu/address/model/attribute/Phone.java:18]: Yeah I agree it can be somewhat restrictive. However I'm not sure how we can only allow "real" numbers without also allowing numbers like "12345".
